### ISSUE TITLE
Uncaught Error: Emitter has been disposed

### ISSUE THREAD

**Issue by NeodarZ** [imdone/imdone-atom-github#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.4
**System**: "Arch Linux"
**Thrown From**: [imdone-atom-github](https://github.com/imdone/imdone-atom-github) package, v0.1.9
### Stack Trace

Uncaught Error: Emitter has been disposed

```
At /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:77

Error: Emitter has been disposed
    at PluginViewInterface.module.exports.Emitter.on (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:77:15)
    at new Plugin (/home/neodarz/.atom/packages/imdone-atom-github/lib/plugin.coffee:39:17)
    at ImdoneAtomView.module.exports.ImdoneAtomView.addPlugin (/home/neodarz/.atom/packages/imdone-atom/lib/imdone-atom-view.coffee:223:20)
    at /home/neodarz/.atom/packages/imdone-atom/lib/imdone-atom-view.coffee:186:10
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Object.module.exports.addPlugin (/home/neodarz/.atom/packages/imdone-atom/lib/plugin-manager.coffee:11:14)
    at Object.module.exports.ImdoneAtomGithub.consumeImdone (/home/neodarz/.atom/packages/imdone-atom-github/lib/imdone-atom-github.coffee:17:13)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```
### Commands

```
     -7:56.6.0 git-control:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -1:17.4.0 core:close (atom-text-editor.editor.is-focused)
     -0:39.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-mixed-indent",
      "linter-stylelint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.20
SFTP-deployment, v1.0.2
atom-beautify, v0.28.26
atom-jshint, v2.0.0
atom-yeoman, v0.3.15
bottom-dock, v0.3.7
color-picker, v2.1.1
git-control, v0.4.0
highlight-selected, v0.11.2
imdone-atom, v1.3.27
imdone-atom-github, v0.1.9
json-schema, v0.1.15
linter, v1.11.3
linter-chktex, v1.2.5
linter-clang, v3.4.4
linter-htmlhint, v1.0.3
linter-jsonlint, v1.1.6
linter-liferay, v2.1.0
linter-manager, v0.2.9
linter-php, v1.2.0
linter-shellcheck, v1.1.0
minimap, v4.20.0
minimap-cursorline, v0.1.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.0
omnisharp-atom, v0.26.14
pigments, v0.24.4
project-view, v0.5.0
project-viewer, v0.2.31
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by amacgregor** [comment]
bump, I'm hitting the same problem and can't get this to work
