### ISSUE TITLE
Uncaught TypeError: Object.observe is not a function

### ISSUE THREAD

**Issue by plashal** [imdone/imdone-atom-github#21]
[Enter steps to reproduce:]

1. Opened up Task Board from the Tree (right click menu) 
2. Gave me this Error

**Atom**: 1.14.2 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [imdone-atom-github](https://github.com/imdone/imdone-atom-github) package 0.1.11

### Stack Trace

Uncaught TypeError: Object.observe is not a function

```
At C:\Users\TildeMoose\.atom\packages\imdone-atom-github\lib\imdone-atom-github-view.coffee:30

TypeError: Object.observe is not a function
    at ImdoneAtomGithubView.module.exports.ImdoneAtomGithubView.handleEvents (/packages/imdone-atom-github/lib/imdone-atom-github-view.coffee:30:12)
    at /packages/imdone-atom-github/lib/imdone-atom-github-view.coffee:21:6)
    at /packages/imdone-atom-github/lib/plugin.coffee:41:19
    at /packages/imdone-atom-github/node_modules/async/lib/async.js:726:13
    at /packages/imdone-atom-github/node_modules/async/lib/async.js:52:16
    at done (/packages/imdone-atom-github/node_modules/async/lib/async.js:246:17)
    at /packages/imdone-atom-github/node_modules/async/lib/async.js:44:16
    at /packages/imdone-atom-github/node_modules/async/lib/async.js:723:17
    at /packages/imdone-atom-github/node_modules/async/lib/async.js:167:37
    at /packages/imdone-atom-github/lib/github-service.coffee:45:7
    at /packages/imdone-atom-github/node_modules/github/api/v3.0.0/user.js:153:17
    at callCallback (/packages/imdone-atom-github/node_modules/github/index.js:743:17)
    at /packages/imdone-atom-github/node_modules/github/index.js:796:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -2:47.8.0 core:paste (input.hidden-input)
     -2:41.2.0 core:save (input.hidden-input)
     -2:34.8.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
  3x -2:06.8.0 imdone-atom:tasks (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
autoclose-html 0.23.0 
color-picker 2.2.5 
file-icons 2.0.15 
git-plus 7.3.0 
highlight-selected 0.12.0 
imdone-atom 2.1.18 
imdone-atom-github 0.1.11 
linter 1.11.23 
linter-csslint 1.3.3 
linter-htmlhint 1.3.1 
linter-jshint 3.0.2 
linter-markdown 3.1.0 
linter-shellcheck 1.4.3 
markdown-toc 0.4.2 
minimap 4.26.8 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-highlight-selected 4.5.0 
pigments 0.39.0 
Remote-FTP 0.10.5 
todo-show 1.10.0 
```

**Comment by rayk** [comment]
Have the same issue.

**Comment by mttfshr** [comment]
Same issue with same steps here

**Comment by mdeuerlein** [comment]
same here.

**Atom:** 1.20.1
**OS:** MacOS HighSierra 10.13 (17A365)
**Package:** imdone-atom-github package 0.1.11
