### ISSUE TITLE
Uncaught TypeError: Cannot read property 'is' of undefined

### ISSUE THREAD

**Issue by imp** [imdone/imdone-atom-github#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [imdone-atom-github](https://github.com/imdone/imdone-atom-github) package, v0.1.3
### Stack Trace

Uncaught TypeError: Cannot read property 'is' of undefined

```
At /Users/cyrilp/.atom/packages/imdone-atom-github/lib/plugin.coffee:40

TypeError: Cannot read property 'is' of undefined
    at /Users/cyrilp/.atom/packages/imdone-atom-github/lib/plugin.coffee:40:26
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at ImdoneAtomView.module.exports.ImdoneAtomView.updateBoard (/Users/cyrilp/.atom/packages/imdone-atom/lib/imdone-atom-view.coffee:360:14)
    at ImdoneAtomView.module.exports.ImdoneAtomView.onRepoUpdate (/Users/cyrilp/.atom/packages/imdone-atom/lib/imdone-atom-view.coffee:236:6)
    at Repository.<anonymous> (/Users/cyrilp/.atom/packages/imdone-atom/lib/imdone-atom-view.coffee:83:8)
    at emitOne (events.js:82:20)
    at Repository.emit (events.js:169:7)
    at /Users/cyrilp/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:951:24
    at /opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:251:17
    at done (/opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:132:19)
    at /opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:32:16
    at /opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:248:21
    at /opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:572:34
    at /Users/cyrilp/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:190:17
    at /Users/cyrilp/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:461:5
    at /Users/cyrilp/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:104:11
    at /Users/cyrilp/.atom/packages/imdone-atom/node_modules/imdone-core/lib/tools.js:220:24
    at FSReqWrap.oncomplete (fs.js:82:15)
```
### Commands

```
     -1:24 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -1:23.5.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -1:22.6.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -1:21.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:20.5.0 editor:newline (atom-text-editor.editor.is-focused)
  7x -1:13.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:46.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:37.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:36.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:36 core:move-down (atom-text-editor.editor.is-focused)
 11x -0:35.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:31.1.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:26.3.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:25.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:16.5.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
     -0:13.5.0 core:cancel (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "projectHome": "~/dev",
    "disabledPackages": [
      "racer"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atomatigit, v1.5.5
autocomplete-python, v0.10.4
build, v0.48.0
build-cargo, v0.6.0
build-make, v0.2.1
imdone-atom, v1.1.60
imdone-atom-github, v0.1.3
language-diff, v0.4.0
language-rust, v0.4.5
linter, v1.11.2
linter-pep8, v1.0.1
linter-rust, v0.2.10
minimap, v4.16.0
minimap-git-diff, v4.1.8
project-manager, v2.6.5
python-tools, v0.6.6
rust-api-docs-helper, v0.5.1
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by piascikj** [comment]
Can you reproduce this error?  Send me the steps if you can.

On Tue, Nov 17, 2015 at 3:56 AM, Cyril Plisko notifications@github.com
wrote:

> [Enter steps to reproduce below:]
> 1. ...
> 2. ...
> 
> _Atom Version_: 1.2.0
> _System_: Mac OS X 10.11.1
> _Thrown From_: imdone-atom-github
> https://github.com/imdone/imdone-atom-github package, v0.1.3
> Stack Trace
> 
> Uncaught TypeError: Cannot read property 'is' of undefined
> 
> At /Users/cyrilp/.atom/packages/imdone-atom-github/lib/plugin.coffee:40
> 
> TypeError: Cannot read property 'is' of undefined
>     at /Users/cyrilp/.atom/packages/imdone-atom-github/lib/plugin.coffee:40:26
>     at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
>     at ImdoneAtomView.module.exports.ImdoneAtomView.updateBoard (/Users/cyrilp/.atom/packages/imdone-atom/lib/imdone-atom-view.coffee:360:14)
>     at ImdoneAtomView.module.exports.ImdoneAtomView.onRepoUpdate (/Users/cyrilp/.atom/packages/imdone-atom/lib/imdone-atom-view.coffee:236:6)
>     at Repository.<anonymous> (/Users/cyrilp/.atom/packages/imdone-atom/lib/imdone-atom-view.coffee:83:8)
>     at emitOne (events.js:82:20)
>     at Repository.emit (events.js:169:7)
>     at /Users/cyrilp/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:951:24
>     at /opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:251:17
>     at done (/opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:132:19)
>     at /opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:32:16
>     at /opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:248:21
>     at /opt/homebrew-cask/Caskroom/atom/1.0.14/Atom.app/Contents/Resources/app.asar/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:572:34
>     at /Users/cyrilp/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:190:17
>     at /Users/cyrilp/.atom/packages/imdone-atom/node_modules/imdone-core/lib/repository.js:461:5
>     at /Users/cyrilp/.atom/packages/imdone-atom/node_modules/imdone-core/lib/mixins/repo-fs-store.js:104:11
>     at /Users/cyrilp/.atom/packages/imdone-atom/node_modules/imdone-core/lib/tools.js:220:24
>     at FSReqWrap.oncomplete (fs.js:82:15)
> 
> Commands
> 
> ```
>  -1:24 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
> ```
> 
>   3x -1:23.5.0 core:move-down (atom-text-editor.editor.is-focused)
>   4x -1:22.6.0 core:move-up (atom-text-editor.editor.is-focused)
>   2x -1:21.3.0 core:move-down (atom-text-editor.editor.is-focused)
>      -1:20.5.0 editor:newline (atom-text-editor.editor.is-focused)
>   7x -1:13.3.0 core:backspace (atom-text-editor.editor.is-focused)
>      -0:46.3.0 editor:newline (atom-text-editor.editor.is-focused)
>      -0:37.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
>   2x -0:36.6.0 core:move-up (atom-text-editor.editor.is-focused)
>      -0:36 core:move-down (atom-text-editor.editor.is-focused)
>  11x -0:35.7.0 core:move-right (atom-text-editor.editor.is-focused)
>      -0:31.1.0 core:save (atom-text-editor.editor.is-focused)
>   3x -0:26.3.0 core:move-down (atom-text-editor.editor.is-focused)
>   2x -0:25.6.0 core:move-up (atom-text-editor.editor.is-focused)
>      -0:16.5.0 imdone-atom:tasks (atom-text-editor.editor.is-focused)
>      -0:13.5.0 core:cancel (atom-pane.pane.active)
> 
> Config
> 
> {
>   "core": {
>     "projectHome": "~/dev",
>     "disabledPackages": [
>       "racer"
>     ]
>   }
> }
> 
> Installed Packages
> 
> # User
> 
> atomatigit, v1.5.5
> autocomplete-python, v0.10.4
> build, v0.48.0
> build-cargo, v0.6.0
> build-make, v0.2.1
> imdone-atom, v1.1.60
> imdone-atom-github, v0.1.3
> language-diff, v0.4.0
> language-rust, v0.4.5
> linter, v1.11.2
> linter-pep8, v1.0.1
> linter-rust, v0.2.10
> minimap, v4.16.0
> minimap-git-diff, v4.1.8
> project-manager, v2.6.5
> python-tools, v0.6.6
> rust-api-docs-helper, v0.5.1
> sync-settings, v0.6.0
> 
> # DevNo dev packages
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/imdone/imdone-atom-github/issues/5.

## 

_Jesse Pia__ś__cik_
Founder @imdoneIO https://twitter.com/imdoneIO | imdone.io
about.me/jesse.piascik
Expert mentor at Codementor.io
www.codementor.io/codewrangler
